### ISSUE TITLE
Wrong: Intel Xeon(R) W-1350 detected as "not supported"

### ISSUE THREAD

**Issue by shamu35** [rcmaehl/WhyNotWin11#657]
I checked with the latest stable and testing release and both tell me that the Intel Xeon(R) W-1350 cpu is not supported.
This is wrong, this cpu is built in in a brandnew Dell Precision 3650 Tower which had Windows 11 factory installed.
Can you fix this detection error? Many thanks

**Comment by rcmaehl** [comment]
Fixed in 664

**Comment by shamu35** [comment]
It's still not working.

 

It tried with the newest "Testing" release and also compiled the project by myself. Both are not detecting the Intel Xeon(R) W-1350 CPU.

See the screenshot

**Comment by rcmaehl** [comment]
Please download

https://raw.githubusercontent.com/rcmaehl/WhyNotWin11/main/includes/SupportedProcessorsIntel.txt

and place in your

%localappdata%\WhyNotWin11 folder

**Comment by shamu35** [comment]
Still not detecting

**Comment by shamu35** [comment]
Hello

I tried with replacing "SupportedProcessorsIntel.txt" in %localappdata%\WhyNotWin11 from here:
https://raw.githubusercontent.com/rcmaehl/WhyNotWin11/main/includes/SupportedProcessorsIntel.txt

It seems that this is only working with the latest testing release. With the latest stable release this file will be overwritten automatically with an older version.

But it does still not detect the Xeon(R) W-1350 cpu. I don't understand why because this cpu is listed in this file but it doesn't work.
We use this tool to scan our network with more than 350 computers and it would be fine if it could detect the compatibility correctly. Do you have an idea why this is not working or what I can try to help solving this problem?

many thanks

**Comment by WilloIzCitron** [comment]
hmm thinks i had a problem, please recheck and take the screenshot of checks

**Comment by shamu35** [comment]
See here the  Xeon(R) W-1350 is not detected correctly
![WhyNotWin11_W20](https://user-images.githubusercontent.com/67783471/159021629-6d002cdc-03c5-4ab8-9039-06be3780ea3d.png)

**Comment by WilloIzCitron** [comment]
use this build from artifact

https://github.com/rcmaehl/WhyNotWin11/actions/runs/1981368141

**Comment by WilloIzCitron** [comment]
oh ik, i forgot to bump version supported intel txt file

**Comment by shamu35** [comment]
Ok found the problem, why the cpu is not correct detected in the latest testing release.

There is an error in file "SupportedProcessorsIntel.txt". Between row 567 and 573 there is a tab instead of a space sign. But depending on the editor you are using, you don't see this tab. I changed these rows (removed the tab) and also changed the version on row 1 to 2.5.0.2 and replaced the file in "%localappdata%\WhyNotWin11" folder and the cpu was detected correctly.

So I think you should fix these rows, see these screenshots here:

wrong, not detected correctly, file is from latest testing release 2.5.0.1:
![not_detected](https://user-images.githubusercontent.com/67783471/159449144-8df10720-0319-4305-a2b9-ddafa73b54a7.png)

Fixed file, detected correctly, file manually changed to 2.5.0.2:
![detected](https://user-images.githubusercontent.com/67783471/159449479-174ef67f-7d5e-468c-9833-a1b829c565ab.png)

**Comment by shamu35** [comment]
I tested again with the "latest testing release" and now the cpu is detected correctly, thanks for your help.

**Comment by WilloIzCitron** [comment]
you're welcome
